Feature/tgg 19
andreysdrv/middle.game.praktikum.yandex pull request #10
Opened 2023-05-03 23:33 UTC by partisan777

верстка страницы лидерборда

2023-05-04 15:34 UTC, keeryl requested changes
Все норм, кроме отсутствия фиксации версии antd

2023-05-04 15:34 UTC, keeryl commented on packages/client/package.json
> +    "antd": "^5.4.4",
Нас учили фиксировать версии.

2023-05-04 21:13 UTC, andreysdrv approved these changes

2023-05-07 13:09 UTC, keeryl approved these changes

2023-05-09 09:35 UTC, merged