dev: ErrorBoundary component is made
andreysdrv/middle.game.praktikum.yandex pull request #14
Opened 2023-05-05 16:09 UTC by keeryl

### Создан компонент ErrorBoundary для обработки ошибок компонентов

2023-05-06 00:01 UTC, keeryl commented
 В документации написано, что можно обернуть все компоненты в роуте на верхнем уровне или оборачивать каждый компонент в отдельности. Не знаю, как лучше реализовать. Если будут идеи пишите. В теории практикума полстраницы и то - ссылка на документацию ректа.

2023-05-06 13:06 UTC, andreysdrv requested changes
Оставил комментарии, которые, на мой взгляд, стоит исправить.
В остальном все отлично :)

2023-05-06 13:06 UTC, andreysdrv commented on packages/client/src/components/ErrorBoudary/ErrorBoundary.tsx
Для единообразия лучше использовать именованный экспорт `export class ErrorBoundary ... `, создать рядом файл `index.ts` и в нём сделать ре-экспорт.
Тогда импорт этого компонента сократиться с `components/ErrorBoudary/ErrorBoundary.tsx` до `components/ErrorBoudary` и автоимпорт в IDE будет более очевидным.

2023-05-06 13:06 UTC, andreysdrv commented on packages/client/src/layouts/Main/Main.tsx
На начальном этапе думаю достаточно будет обернуть всё приложение в один обработчик ошибок и лучше это сделать прямо в компоненте `App` что бы не засорять `Layout`

2023-05-07 13:19 UTC, keeryl commented on packages/client/src/layouts/Main/Main.tsx
> На начальном этапе думаю достаточно будет обернуть всё приложение в один обработчик ошибок и лучше это сделать прямо в компоненте `App` что бы не засорять `Layout`

 Обернул <App/>

2023-05-07 13:20 UTC, keeryl commented on packages/client/src/components/ErrorBoudary/ErrorBoundary.tsx
> Для единообразия лучше использовать именованный экспорт `export class ErrorBoundary ... `, создать рядом файл `index.ts` и в нём сделать ре-экспорт. Тогда импорт этого компонента сократиться с `components/ErrorBoudary/ErrorBoundary.tsx` до `components/ErrorBoudary` и автоимпорт в IDE будет более очевидным.

Ок. Сделал.

2023-05-08 09:20 UTC, andreysdrv approved these changes

2023-05-09 09:38 UTC, merged