Feature/tgg 42 - Создание стора на redux-toolkit
andreysdrv/middle.game.praktikum.yandex pull request #20
Opened 2023-05-17 17:36 UTC by keeryl

Создание стора на redux-toolkit

2023-05-17 19:23 UTC, andreysdrv approved these changes
Думаю, нужно добавить селекторы для получения данных из стора (состояние загрузки и данных пользователя) и уже использовать их на странице Profile.

В остальном всё ок! :)

2023-05-17 23:52 UTC, keeryl commented
> 



> 



> 



> Думаю, нужно добавить селекторы для получения данных из стора (состояние загрузки и данных пользователя) и уже использовать их на странице Profile.
> 
> В остальном всё ок! :)

Я пытался сделать селекторы в отдельном файле, но реакт ругается, что нужно использовать хуки только внутри функциональных компонентах. Поэтому селекторы создал в профиле и хедере.

2023-05-18 07:20 UTC, DazzlingFame requested changes
Привет, хорошая работа, оставил комментарии в коде

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/api/UserApi/types.ts
> +}
Проверь форматирование в изменениях. Вижу опять, будто бы не запускался prettier (тут нет пустой строки в конце файла, дальше в `Header` нет пробела после `user` - `<div>{user&& user.login}</div>`) И так далее

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/components/Header/Header.tsx
> +        <div>{user&& user.login}</div>
Тут можно не рисовать весь `div`, если нет `user`

```suggestion
        {!!user && (<div>{user.login}</div>)}
```

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/controllers/UserController/UserController.ts
> +      alert(e)
А что в этом случае `e`? Как будет выглядеть подобный алерт, если придёт ошибка с бэкенда?

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
>          <ChangeProfileModal /> */
Вижу, что закомментированный код просочился в мейн ветку мимо меня. Выпили его в этом ПР, пожалуйста.

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +  const user = useAppSelector(state => state.user.data);
Видел комментарий про селекторы. Тебе не надо выносить весь хук, надо вынести только то, что лежит внутри хука.

Те ты создашь методы (я писал прямо тут, нужна будет ещё типизация)
```
const selectUser = (state) => state.user;
const selectUserData = (state) => selectUser(state).data;
```

и в компоненте будешь вызывать такое
`  const user = useAppSelector(selectUserData);
`

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +  const user = useAppSelector(state => state.user.data);
Это сильно поможет, когда редакс разрастётся, и не придётся думать, где что лежит

2023-05-18 07:20 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +          <Col span={4}>{user&& user.email}</Col>
Тут и везде дальше лучше вообще не рендерить компонент, если у него нет контента
```suggestion
          {!!user && (<Col span={4}>{user.email}</Col>)}
```

2023-05-18 07:47 UTC, go-pro0000 approved these changes

2023-05-18 15:08 UTC, keeryl commented on packages/client/src/api/UserApi/types.ts
> +}
Ок. Запущу prettier

2023-05-18 15:09 UTC, keeryl commented on packages/client/src/components/Header/Header.tsx
> +        <div>{user&& user.login}</div>
> Тут можно не рисовать весь `div`, если нет `user`

Попробовал. Выдает ошибку - React.Children.only expected to receive a single React element child.

Нужен хотя бы один элемент.

2023-05-18 15:10 UTC, keeryl commented on packages/client/src/controllers/UserController/UserController.ts
> +      alert(e)
> А что в этом случае `e`? Как будет выглядеть подобный алерт, если придёт ошибка с бэкенда?

Пока не придумали. Может убрать блок try/catch и обрабатывать ошибки в санках?

2023-05-18 15:12 UTC, keeryl commented on packages/client/src/pages/Profile/UserDataBlock.tsx
>          <ChangeProfileModal /> */
> Вижу, что закомментированный код просочился в мейн ветку мимо меня. Выпили его в этом ПР, пожалуйста.

Выпилил

2023-05-18 15:32 UTC, keeryl commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +  const user = useAppSelector(state => state.user.data);
> const selectUser = (state) => state.user;

Получилось. Еще не запушил.

2023-05-18 16:01 UTC, keeryl commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +          <Col span={4}>{user&& user.email}</Col>
> Тут и везде дальше лучше вообще не рендерить компонент, если у него нет контента

Сделал

2023-05-19 10:27 UTC, DazzlingFame commented on packages/client/src/components/Header/Header.tsx
> +        <div>{user&& user.login}</div>
Тогда получается можно не рисовать весь родительский компонент

2023-05-19 10:28 UTC, DazzlingFame commented on packages/client/src/controllers/UserController/UserController.ts
> +      alert(e)
Да, если у вас есть возможность использовать готовый обработчик, то используйте его

2023-05-19 10:28 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +  const user = useAppSelector(state => state.user.data);
Отлично!

2023-05-19 10:30 UTC, DazzlingFame commented
@keeryl ответил на вопросы, зарезолвил часть комментариев

2023-05-19 13:48 UTC, keeryl commented on packages/client/src/components/Header/Header.tsx
> +        <div>{user&& user.login}</div>
> Тогда получается можно не рисовать весь родительский компонент

Ок. Сделал

2023-05-19 13:48 UTC, keeryl commented on packages/client/src/controllers/UserController/UserController.ts
> +      alert(e)
> Да, если у вас есть возможность использовать готовый обработчик, то используйте его

Ок. Поставил обработчик ошибок, созданный ранее

2023-05-19 14:44 UTC, keeryl commented
> @keeryl ответил на вопросы, зарезолвил часть комментариев

Исправил остальные комменты

2023-05-19 18:03 UTC, DazzlingFame approved these changes
👍

2023-05-19 21:25 UTC, merged