Feature/tgg 14
andreysdrv/middle.game.praktikum.yandex pull request #4
Opened 2023-04-28 15:52 UTC by keeryl

### Создание страницы логина и логика авторизации

2023-04-28 18:28 UTC, andreysdrv requested changes
- Фоновые изображения стоит экспортировать из фигмы в png формате и прогнать их через [этот сервис](https://tinypng.com/). Это значительно уменьшит их вес.
- Так же для фона нужно добавить свойство `background-size: cover`,
- Папку `Api` нужно перенести в `src` и назвать с маленькой буквы для единообразия 

В остальном всё ок :)

2023-04-28 18:28 UTC, andreysdrv commented on packages/client/Api/AuthApi.ts
> +const baseUrl = 'https://ya-praktikum.tech/api/v2';
Базовый url лучше вынести в отдельный файл, например, config или constants и поместить его в папке src, что бы не дублировать его позже в других контроллерах

2023-04-29 06:32 UTC, partisan777 reviewed
вроде все норм

2023-04-29 11:38 UTC, andreysdrv approved these changes

2023-05-02 07:21 UTC, DazzlingFame commented
Привет, ожидаю перед передачей мне на ревью (писал об этом в пачке)
- 2 аппрува от команды
- более менее подробное описание изменений
- скриншоты или видео, если поменялся UI (тут, как я понимаю, поменялся)

2023-05-02 16:14 UTC, keeryl commented
> Привет, ожидаю перед передачей мне на ревью (писал об этом в пачке)
> 
> * 2 аппрува от команды (не требую, но рекомендую)
> * более менее подробное описание изменений
> * скриншоты или видео, если поменялся UI (тут, как я понимаю, поменялся)

Ссылка на макет: https://www.figma.com/file/XWdsXuIbAQCTUmBswe43KK/Awesome-Battle-City?type=design&node-id=0-1&t=Ituwl8RnGHZBy1JE-0

Изменения: была создана страница логина с использованием antDesign. Инпутам добавлена валидация. Также было подключено api Яндекса из первого модуля для логина пользователя. Кнопка сабмита сабмита дизейблится, если правила валидации инпутов не пройдены.

<img width="1130" alt="Снимок экрана 2023-05-02 в 19 14 21" src="https://user-images.githubusercontent.com/76181856/235724258-51f10576-3f5e-450a-a6fd-9dfe8550dc11.png">

2023-05-02 20:01 UTC, DazzlingFame reviewed
Привет, хорошая работа, оставил комментарии в коде.

Плюс общий комментарий по стилю. По коду сильно заметно, что нет общего стиля форматирования. Местами табуляция в 2 пробела, местами в 4, нет пустых строк в конце файлов и так далее.

С этим вам поможет утилита - `prettier`. Советую обсудить с командой на очередной встрече или в чате и подключить её. Код будет выглядеть сильно приятнее и более читаемым.

Это не требование к этому реквесту, а скорее пожелание, со временем, когда проект разрастётся `prettier` вам сильно поможет проще ориентироваться в коде

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/api/AuthApi.ts
> +// }
Закомментированный код лучше никогда не вливать в мейн ветку. Её состояние всегда стоит держать актуальным и без лишнего кода. 

В крайнем случае, если этот код критически важен, стоит отписать комментарий, зачем он нужен, и приложить там же ссылку на задачу, где это будет исправлено

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/utils/constants.ts
> +export const baseUrl = 'https://ya-praktikum.tech/api/v2';
Хардкодные константы по гайдам лучше называть через `snake_case` в высоком регистре, чтобы их можно было легко отличить от переменных и констант, инициализирующихся в рантайме.

Тут будет:

`BASE_URL` или лучше `API_BASE_URL`

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/api/AuthApi.ts
> +export default new AuthApi(baseUrl);
В конце файлов традиционно желательно оставлять пустую строку. Тут же об этом говорит UI гитхаба

<img width="364" alt="image" src="https://user-images.githubusercontent.com/15292833/235769350-4abe6177-abf9-49ab-845c-55e1c927f356.png">

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +    }, []);
В мейн ветке нужен этот лог? Вообще `console.log` не рекомендуется вливать в мейн ветки вообще. Иначе в очередной раз их начнут видеть обычные пользователи в продакшне

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +    const [ isLoading, setIsLoading ] = useState<boolean>(false);
Не обязательно править, но если ты указываешь дефолтное значение в `useState`, то тип явно можно не указывать
```suggestion
    const [ isLoading, setIsLoading ] = useState(false);
```

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +            })
Такая конструкция скорее всего будет повторяться где-то ещё в вашем приложении.

Хорошо было бы вынести эту обработку в коммон утилиту, принимать там на вход код ошибки и вызывать `message` с правильным ответом, чтобы не плодить одинаковый код

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?![\W_|-]{1})(?!.*_-)(?!.*-_)(?!.*--)(?!.*__).[\w-]*(?<!.-|_)$/gi.test(value) ?
Строку валидатора точно стоит вынести в отдельную константу и не ухудшать читаемость верстки

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                        validateFirst={true}
Вижу, что тут через 1 мешается стилизация через `className` и через `style`. Хотя бы в рамках одного компонента это точно стоит привести к единообразию

2023-05-02 20:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?=.*?[0-9])(?=.*?[A-Z]).*$/.test(value) ?
Стоит вынести правило валидации в константу с говорящим названием

2023-05-02 20:33 UTC, partisan777 reviewed
ok

2023-05-02 20:35 UTC, partisan777 approved these changes
ok

2023-05-03 15:45 UTC, DazzlingFame commented
@keeryl Отписывайся плз в ветках комментариев, если ты сделал что-то по этому конкретному комменту. Это сильно ускоряет обработку правок

2023-05-03 17:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?=.*?[0-9])(?=.*?[A-Z]).*$/.test(value) ?
Не заметил тут изменений

2023-05-03 17:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                        validateFirst={true}
Не заметил тут изменений

2023-05-03 17:01 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?![\W_|-]{1})(?!.*_-)(?!.*-_)(?!.*--)(?!.*__).[\w-]*(?<!.-|_)$/gi.test(value) ?
Не заметил тут изменений

2023-05-03 17:02 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +            })
Не заметил тут изменений

2023-05-03 17:02 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +    }, []);
Не заметил тут изменений

2023-05-04 15:38 UTC, keeryl commented
> @keeryl Отписывайся плз в ветках комментариев, если ты сделал что-то по этому конкретному комменту. Это сильно ускоряет обработку правок

ОК

2023-05-04 15:40 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?=.*?[0-9])(?=.*?[A-Z]).*$/.test(value) ?
> Не заметил тут изменений

Я оставлял комментарий в коде. Наверное prettier его удалил. Я пытался вынести регулярку в папку utils как константу и импортировать и использовать. Но тогда валидация не отрабатывает почему-то как прежде. Можно ли оставить так?

2023-05-04 15:44 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +                        validateFirst={true}
> Не заметил тут изменений

Я оставлял комментарий в коде. Наверное prettier его удалил. Я пробовал вынести все в стили и делать только через className, но тогда некоторые стили не применяются (не перезаписываются), например в Typography.Title свойство font-size в стилях css не отрабатывает, а если записать его в атрибут style компонента, то все работает и стиль применяется. Можно ли оставить так?

2023-05-04 15:45 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?![\W_|-]{1})(?!.*_-)(?!.*-_)(?!.*--)(?!.*__).[\w-]*(?<!.-|_)$/gi.test(value) ?
> Не заметил тут изменений

Я оставлял комментарий в коде. Наверное prettier его удалил. Я пытался вынести регулярку в папку utils как константу и импортировать и использовать. Но тогда валидация не отрабатывает почему-то как прежде. Можно ли оставить так?

2023-05-04 15:50 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +            })
> Не заметил тут изменений

Я подумал, что это не обязательно к изменению. Повторяться будут ошибки с текстом для ошибки 400 и 500. Для 401 наверное будет что-то другое на странице регистрации. Я правильно понял, что ты предлагаешь вынести в utils функцию, например, handleLoginAuthErrors() и вызывать ее в catch этого запроса?

2023-05-04 15:54 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +    }, []);
> В мейн ветке нужен этот лог? Вообще `console.log` не рекомендуется вливать в мейн ветки вообще. Иначе в очередной раз их начнут видеть обычные пользователи в продакшне

Этот кусок кода я удалял. Если он остался, я его удалю и проверю, чтобы его не было.

2023-05-05 07:06 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +            })
Я тут имел ввиду общую утилиту вообще для всех запросов, не только авторизации и регистрации. В 401 можно писать, например, "Ошибка авторизации" это же и так код `Unauthorized`

Целевое состояние вижу так:
`.catch(handleHttpErrors)`

Если важно показать именно, что логин и пароль не верны, то можешь вынести чисто для ошибок авторизации, но главное, что этому коду не место в компоненте. Его надо вынести либо в обработку API метода, либо в утилиту, как я предлагаю

2023-05-05 07:14 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?![\W_|-]{1})(?!.*_-)(?!.*-_)(?!.*--)(?!.*__).[\w-]*(?<!.-|_)$/gi.test(value) ?
Так точно оставлять нельзя, потому что в таком виде при взгляде на код абсолютно непонятно, что этот валидатор проверяет.

2023-05-05 07:40 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?![\W_|-]{1})(?!.*_-)(?!.*-_)(?!.*--)(?!.*__).[\w-]*(?<!.-|_)$/gi.test(value) ?
Я не очень знаком с `antd`. Можешь уточнить особенности валидации у участников команды, которые его предложили.

В крайнем случае, если не получится вынести валидаторы отдельно, можешь вынести `Form.Item` в отдельные компоненты в папке `Login`. Отдельно в компонент форму логина, отдельно пароля И так далее

чтобы вместо огромных `Form.Item` в странице `Login` было что-то такое:

<LoginFormItem />
<PasswordFormItem />
<LoginSubmitButton />

2023-05-05 07:43 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                        validateFirst={true}
Не знаком с `antd`, но обычно в дизайн системах `Typography` вообще не подразумевает перезаписывание текстовых стилей. Обычно `Typography` созданы, чтобы просто брать компоненты-пресеты. Почему тут вообще появилась необходимость перезаписывать базовые стили дизайн системы?

2023-05-05 07:43 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?=.*?[0-9])(?=.*?[A-Z]).*$/.test(value) ?
Отписал в комментарии выше

2023-05-05 07:44 UTC, DazzlingFame commented on packages/client/src/pages/Login/Login.tsx
> +export { Login };
Тут опять пропала пустая строка внизу файла.

Обычно в IDE можно настроить вызов prettier на сохранение файла. Это может помочь с такими местами

2023-05-05 17:01 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?=.*?[0-9])(?=.*?[A-Z]).*$/.test(value) ?
> Стоит вынести правило валидации в константу с говорящим названием

Сделал

2023-05-05 17:01 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +                        validateFirst={true}
> Не знаком с `antd`, но обычно в дизайн системах `Typography` вообще не подразумевает перезаписывание текстовых стилей. Обычно `Typography` созданы, чтобы просто брать компоненты-пресеты. Почему тут вообще появилась необходимость перезаписывать базовые стили дизайн системы?

Оставил только className

2023-05-05 17:02 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +                                   return /^(?![\W_|-]{1})(?!.*_-)(?!.*-_)(?!.*--)(?!.*__).[\w-]*(?<!.-|_)$/gi.test(value) ?
> Я не очень знаком с `antd`. Можешь уточнить особенности валидации у участников команды, которые его предложили.
> 
> В крайнем случае, если не получится вынести валидаторы отдельно, можешь вынести `Form.Item` в отдельные компоненты в папке `Login`. Отдельно в компонент форму логина, отдельно пароля И так далее
> 
> чтобы вместо огромных `Form.Item` в странице `Login` было что-то такое:
> 
> И плюс рядом с регулярками, которые не получилось вынести, написать комментарий в коде, на что они проверяют и как должны работать

Я сделал валидацию немного по другому и регулярку вынес в константу. Валидация отрабатывает как ожидается.

2023-05-05 17:03 UTC, keeryl commented on packages/client/src/pages/Login/Login.tsx
> +            })
> Я тут имел ввиду общую утилиту вообще для всех запросов, не только авторизации и регистрации. В 401 можно писать, например, "Ошибка авторизации" это же и так код `Unauthorized`
> 
> Целевое состояние вижу так: `.catch(handleHttpErrors)`
> 
> Если важно показать именно, что логин и пароль не верны, то можешь вынести чисто для ошибок авторизации, но главное, что этому коду не место в компоненте. Его надо вынести либо в обработку API метода, либо в утилиту, как я предлагаю

Сделал

2023-05-05 18:42 UTC, DazzlingFame approved these changes
👍

2023-05-05 23:58 UTC, merged