Feature/tgg 21
andreysdrv/middle.game.praktikum.yandex pull request #6
Opened 2023-04-29 13:45 UTC by partisan777

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-30 10:18 UTC, andreysdrv submitted a review, later dismissed

2023-04-30 12:29 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +    const showModalChangeProfile = () => {
Эту логику можно объединить в одну функцию с вызовом setIsModalOpenChangeProfile(!isModalOpenChangeProfile))

2023-04-30 12:31 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +    const showModalChangePassword = () => {
Тут аналогично можно вызвать функцию setter с !state

2023-04-30 12:33 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +  return ( <div className={styles.main}>
я бы использовал семантичный тег main

2023-04-30 12:35 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +              rules={[
Можно бы добавить правило на проверку совпадения пароля

2023-04-30 12:37 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +                rules={[
Можно добить правило нп проверку валидности почты и чтобы новая почта отличалась от предыдущей

2023-04-30 12:39 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +                  required: true,
Можно добавить правила на валидациб никнейма и на отлитчие нового никнейма от предыдущего

2023-04-30 12:41 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +                <Button type="primary" htmlType="submit">
Можно добавить disable для кнопки, если данные инпуты невалидны

2023-04-30 12:44 UTC, keeryl commented on packages/client/src/pages/Profile/Profile.tsx
> +            <img className={styles.avatar} src={userData.avatar} alt="Avatar"/>
Не увидел модалку для изменения аватара

2023-04-30 12:46 UTC, keeryl requested changes
У нас еще есть данные профиля: first_name, display_name, phone. Инпут для никнейма должен называться display_name.

2023-05-01 22:05 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +              rules={[
логика работы обновления и т.д. сейчас не реализуется.

2023-05-01 22:06 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +                  required: true,
логика не реализуется сейчас

2023-05-01 22:34 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +                <Button type="primary" htmlType="submit">
бантик))

2023-05-01 22:35 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +                rules={[
чтобы отличалась от предыдущей надо делать на стороне сервера, ИМХО

2023-05-01 22:36 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +  return ( <div className={styles.main}>
поменял

2023-05-01 22:51 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +            <img className={styles.avatar} src={userData.avatar} alt="Avatar"/>
добавил кнопку загрузки для аватара на модалку изменения данных профиля

2023-05-02 09:09 UTC, andreysdrv commented
Пайплайн падает из-за ошибок типизации.
Обрати внимание на [пример](https://codesandbox.io/s/qnu4zb?file=/demo.tsx) из ant design.
Нужно импортировать тип пропсов `import type { UploadProps } from 'antd'` и сослаться на него при объявлении этих пропсов
```
const props: UploadProps = {
  action: ...,
  onChange(info) {
    ...
  }
}
```

2023-05-02 15:04 UTC, keeryl approved these changes

2023-05-06 19:50 UTC, andreysdrv approved these changes

2023-05-10 09:19 UTC, DazzlingFame requested changes
Привет, хорошая работа! Оставил комментарии в коде.

Обрати внимание на вынесение компонентов и форматирование

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/Profile.tsx
> +      console.log(values);
Если ты не хочешь, чтобы пользователи видели эту консоль, лучше её убрать

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/Profile.tsx
> +      console.log(values);
Если ты не хочешь, чтобы пользователи видели эту консоль, лучше её убрать

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/Profile.tsx
> +    };
- хардкодные константы стоит называть в стиле `TAIL_LAYOUT`
- если переменная не имеет зависимости от компонента, то стоит вынести её наружу, чтобы она не пересоздавалась на каждом его ререндере

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/Profile.tsx
> +          console.log(info.file, info.fileList);
Если ты не хочешь, чтобы пользователи видели эту консоль, лучше её убрать

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/Profile.tsx
> +              <Divider orientation="left"></Divider>
Тут получилось очень большое нагромождение верстки. 

По своему опыту советую, что если после `return` в компоненте получается больше 80-100 строк кода, то стоит сильно задуматься над тем, чтобы разделить верстку на отдельные компоненты в отдельных файлах, даже если они не будут переиспользоваться.

Тут вижу у тебя в стилизации `styles.block`, как минимум можно разделить на компоненты по этим блокам

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/const.tsx
> +export type UserProps = {
Типы лучше вынести из файла "константы" в файл "типы", чтобы всё было прозрачно

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/const.tsx
> +
Тут странные пустые строки, + видел пару мест, где были проблемы с табуляцией. Запуск `prettier` должен помочь

2023-05-10 09:19 UTC, DazzlingFame commented on packages/client/src/pages/Profile/const.tsx
> +    userId: 1,
Хардкодные константы стоит именовать в стиле `USER_DATA`, чтобы отличать их от констант, которые инициализируются в рантайме

2023-05-10 17:30 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +      console.log(values);
это для дебага, потом, после реализации функционала уберу

2023-05-10 17:30 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +      console.log(values);
это для дебага, потом, после реализации функционала уберу

2023-05-10 17:48 UTC, partisan777 commented on packages/client/src/pages/Profile/const.tsx
> +    userId: 1,
исправлено

2023-05-10 17:49 UTC, partisan777 commented on packages/client/src/pages/Profile/const.tsx
> +
исправил

2023-05-10 17:49 UTC, partisan777 commented on packages/client/src/pages/Profile/const.tsx
> +export type UserProps = {
исправил

2023-05-10 18:25 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +              <Divider orientation="left"></Divider>
исправил по блокам и разнес

2023-05-10 18:26 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +          console.log(info.file, info.fileList);
это для дебага, после реализации функционала уберу

2023-05-10 18:26 UTC, partisan777 commented on packages/client/src/pages/Profile/Profile.tsx
> +    };
исправил

2023-05-11 07:22 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +      console.log(values);
console.log не должно быть в мейн ветке. Это инструмент для дебага в твоем случае. Если хочешь демонстрировать, что что-то происходит по клику на кнопку, то используй для этого `message` или `alert`. Это относится ко всем консолям в изменениях

2023-05-11 07:27 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +)};
Всё ещё замечаю тут проблемы с форматированием, например тут не хватает пустой строки в конце файла, ниже html странно начинается сразу после return
<img width="343" alt="image" src="https://github.com/andreysdrv/middle.game.praktikum.yandex/assets/15292833/82fe813a-ef4e-49ad-bf9a-ff11c57cbc20">

<img width="244" alt="image" src="https://github.com/andreysdrv/middle.game.praktikum.yandex/assets/15292833/23a9f6f6-72a9-41d6-abd0-38cd4ed82bdd">

2023-05-11 07:29 UTC, DazzlingFame commented on packages/client/src/pages/Profile/UserDataBlock.tsx
> +    <Modal title="Изменить данные"
Верстки всё ещё слишком много для 1 файла. Почти 200 строк. Это будет очень сложно переваривать даже тебе самому, если ты вернешься к этому коду через пару месяцев.

Давай вынесем в отдельные компоненты обе модалки, это должно помочь

2023-05-12 06:46 UTC, DazzlingFame approved these changes
Круто, стало значительно лучше выглядеть. Вынос компонентов разнёс ответственность за верстку по своим файлам, и ориентироваться стало намного проще 👍

2023-05-13 15:05 UTC, merged