tgg-16 верстка страницы форума
andreysdrv/middle.game.praktikum.yandex pull request #9
Opened 2023-05-03 22:36 UTC by partisan777

страница форума

2023-05-04 15:30 UTC, keeryl requested changes
Пожалуй единственный запрос на изменения - фиксировать версию "react-dom".

По поводу закомментированного кода - наш ревьюер просит его либо удалить либо объяснить почему он закомментирвоан.

Также ревьюер меня попросил сделать скрин страницы - показать что сделано. И прикрепить скрин к пулреквесту. Это я не прошу сделать, просто предупреждаю.

2023-05-04 15:30 UTC, keeryl commented on packages/client/src/pages/Forum/Forum.tsx
> +  // useEffect(() => {
Меня рьвюер попросил либо объяснить закомментированный код, либо его удалить. Исправлять не требуется.

2023-05-04 15:30 UTC, keeryl commented on packages/client/package.json
> +    "react-dom": "^18.2.0",
Нас учили, что правильнее фиксировать версии.

2023-05-04 15:30 UTC, keeryl commented on packages/client/src/pages/Forum/Forum.tsx
> +    setIsModalOpenAddPost(true);
Не хочешь сделать setIsModalOpenAddPost(!isModalOpenAddPost) ? Исправлять не требуется

2023-05-04 15:30 UTC, keeryl commented on packages/client/src/pages/Forum/forum.module.css
> +    /* display: flex; */
Почему закомментировал?

2023-05-04 21:16 UTC, andreysdrv requested changes

2023-05-04 21:16 UTC, andreysdrv commented on packages/client/package.json
> +    "react-dom": "^18.2.0",
Да, версии лучше зафиксировать

2023-05-04 21:16 UTC, andreysdrv commented on packages/client/src/pages/Forum/Forum.tsx
> +  // useEffect(() => {
Закомментированный код стоит убрать, что бы не засорять dev ветку

2023-05-07 12:59 UTC, andreysdrv approved these changes

2023-05-07 13:09 UTC, keeryl approved these changes

2023-05-09 09:36 UTC, merged